# coding: utf-8

"""
    Apollo OpenAPI

    <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from apollo_openapi.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_namespaces_integrity_check.get import CheckNamespaceIntegrity
from apollo_openapi.paths.openapi_v1_apps_app_id_appnamespaces.post import CreateNamespace
from apollo_openapi.paths.openapi_v1_apps_app_id_appnamespaces_namespace_name.delete import DeleteAppNamespace
from apollo_openapi.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_namespaces_namespace_name_links.delete import DeleteNamespaceLinks
from apollo_openapi.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces.get import FindNamespaces
from apollo_openapi.paths.openapi_v1_apps_app_id_appnamespaces_namespace_name.get import GetAppNamespace
from apollo_openapi.paths.openapi_v1_appnamespaces.get import GetAppNamespaces
from apollo_openapi.paths.openapi_v1_apps_app_id_appnamespaces.get import GetAppNamespacesByApp
from apollo_openapi.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_lock.get import GetNamespaceLock
from apollo_openapi.paths.openapi_v1_apps_app_id_namespaces_releases_status.get import GetNamespacesReleaseStatus
from apollo_openapi.paths.openapi_v1_envs_env_appnamespaces_public_namespace_name_instances.get import GetPublicAppNamespaceInstances
from apollo_openapi.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_namespaces_namespace_name_public_association.get import GetPublicNamespaceAssociation
from apollo_openapi.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name.get import LoadNamespace


class NamespaceManagementApi(
    CheckNamespaceIntegrity,
    CreateNamespace,
    DeleteAppNamespace,
    DeleteNamespaceLinks,
    FindNamespaces,
    GetAppNamespace,
    GetAppNamespaces,
    GetAppNamespacesByApp,
    GetNamespaceLock,
    GetNamespacesReleaseStatus,
    GetPublicAppNamespaceInstances,
    GetPublicNamespaceAssociation,
    LoadNamespace,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
