/*
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.OpenUserInfoDTO;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * OpenClusterNamespaceRoleUserDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class OpenClusterNamespaceRoleUserDTO {
  public static final String SERIALIZED_NAME_APP_ID = "appId";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  private String appId;

  public static final String SERIALIZED_NAME_ENV = "env";
  @SerializedName(SERIALIZED_NAME_ENV)
  private String env;

  public static final String SERIALIZED_NAME_CLUSTER = "cluster";
  @SerializedName(SERIALIZED_NAME_CLUSTER)
  private String cluster;

  public static final String SERIALIZED_NAME_MODIFY_ROLE_USERS = "modifyRoleUsers";
  @SerializedName(SERIALIZED_NAME_MODIFY_ROLE_USERS)
  private List<OpenUserInfoDTO> modifyRoleUsers;

  public static final String SERIALIZED_NAME_RELEASE_ROLE_USERS = "releaseRoleUsers";
  @SerializedName(SERIALIZED_NAME_RELEASE_ROLE_USERS)
  private List<OpenUserInfoDTO> releaseRoleUsers;

  public OpenClusterNamespaceRoleUserDTO() {
  }

  public OpenClusterNamespaceRoleUserDTO appId(String appId) {

    this.appId = appId;
    return this;
  }

   /**
   *
   * @return appId
  **/
  @javax.annotation.Nullable
  public String getAppId() {
    return appId;
  }


  public void setAppId(String appId) {
    this.appId = appId;
  }


  public OpenClusterNamespaceRoleUserDTO env(String env) {

    this.env = env;
    return this;
  }

   /**
   *
   * @return env
  **/
  @javax.annotation.Nullable
  public String getEnv() {
    return env;
  }


  public void setEnv(String env) {
    this.env = env;
  }


  public OpenClusterNamespaceRoleUserDTO cluster(String cluster) {

    this.cluster = cluster;
    return this;
  }

   /**
   *
   * @return cluster
  **/
  @javax.annotation.Nullable
  public String getCluster() {
    return cluster;
  }


  public void setCluster(String cluster) {
    this.cluster = cluster;
  }


  public OpenClusterNamespaceRoleUserDTO modifyRoleUsers(List<OpenUserInfoDTO> modifyRoleUsers) {

    this.modifyRoleUsers = modifyRoleUsers;
    return this;
  }

  public OpenClusterNamespaceRoleUserDTO addModifyRoleUsersItem(OpenUserInfoDTO modifyRoleUsersItem) {
    if (this.modifyRoleUsers == null) {
      this.modifyRoleUsers = new ArrayList<>();
    }
    this.modifyRoleUsers.add(modifyRoleUsersItem);
    return this;
  }

   /**
   *
   * @return modifyRoleUsers
  **/
  @javax.annotation.Nullable
  public List<OpenUserInfoDTO> getModifyRoleUsers() {
    return modifyRoleUsers;
  }


  public void setModifyRoleUsers(List<OpenUserInfoDTO> modifyRoleUsers) {
    this.modifyRoleUsers = modifyRoleUsers;
  }


  public OpenClusterNamespaceRoleUserDTO releaseRoleUsers(List<OpenUserInfoDTO> releaseRoleUsers) {

    this.releaseRoleUsers = releaseRoleUsers;
    return this;
  }

  public OpenClusterNamespaceRoleUserDTO addReleaseRoleUsersItem(OpenUserInfoDTO releaseRoleUsersItem) {
    if (this.releaseRoleUsers == null) {
      this.releaseRoleUsers = new ArrayList<>();
    }
    this.releaseRoleUsers.add(releaseRoleUsersItem);
    return this;
  }

   /**
   *
   * @return releaseRoleUsers
  **/
  @javax.annotation.Nullable
  public List<OpenUserInfoDTO> getReleaseRoleUsers() {
    return releaseRoleUsers;
  }


  public void setReleaseRoleUsers(List<OpenUserInfoDTO> releaseRoleUsers) {
    this.releaseRoleUsers = releaseRoleUsers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenClusterNamespaceRoleUserDTO openClusterNamespaceRoleUserDTO = (OpenClusterNamespaceRoleUserDTO) o;
    return Objects.equals(this.appId, openClusterNamespaceRoleUserDTO.appId) &&
        Objects.equals(this.env, openClusterNamespaceRoleUserDTO.env) &&
        Objects.equals(this.cluster, openClusterNamespaceRoleUserDTO.cluster) &&
        Objects.equals(this.modifyRoleUsers, openClusterNamespaceRoleUserDTO.modifyRoleUsers) &&
        Objects.equals(this.releaseRoleUsers, openClusterNamespaceRoleUserDTO.releaseRoleUsers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, env, cluster, modifyRoleUsers, releaseRoleUsers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenClusterNamespaceRoleUserDTO {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    env: ").append(toIndentedString(env)).append("\n");
    sb.append("    cluster: ").append(toIndentedString(cluster)).append("\n");
    sb.append("    modifyRoleUsers: ").append(toIndentedString(modifyRoleUsers)).append("\n");
    sb.append("    releaseRoleUsers: ").append(toIndentedString(releaseRoleUsers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("appId");
    openapiFields.add("env");
    openapiFields.add("cluster");
    openapiFields.add("modifyRoleUsers");
    openapiFields.add("releaseRoleUsers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to OpenClusterNamespaceRoleUserDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!OpenClusterNamespaceRoleUserDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OpenClusterNamespaceRoleUserDTO is not found in the empty JSON string", OpenClusterNamespaceRoleUserDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!OpenClusterNamespaceRoleUserDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OpenClusterNamespaceRoleUserDTO` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("appId") != null && !jsonObj.get("appId").isJsonNull()) && !jsonObj.get("appId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `appId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("appId").toString()));
      }
      if ((jsonObj.get("env") != null && !jsonObj.get("env").isJsonNull()) && !jsonObj.get("env").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `env` to be a primitive type in the JSON string but got `%s`", jsonObj.get("env").toString()));
      }
      if ((jsonObj.get("cluster") != null && !jsonObj.get("cluster").isJsonNull()) && !jsonObj.get("cluster").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cluster` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cluster").toString()));
      }
      if (jsonObj.get("modifyRoleUsers") != null && !jsonObj.get("modifyRoleUsers").isJsonNull()) {
        JsonArray jsonArraymodifyRoleUsers = jsonObj.getAsJsonArray("modifyRoleUsers");
        if (jsonArraymodifyRoleUsers != null) {
          // ensure the json data is an array
          if (!jsonObj.get("modifyRoleUsers").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `modifyRoleUsers` to be an array in the JSON string but got `%s`", jsonObj.get("modifyRoleUsers").toString()));
          }

          // validate the optional field `modifyRoleUsers` (array)
          for (int i = 0; i < jsonArraymodifyRoleUsers.size(); i++) {
            OpenUserInfoDTO.validateJsonObject(jsonArraymodifyRoleUsers.get(i).getAsJsonObject());
          };
        }
      }
      if (jsonObj.get("releaseRoleUsers") != null && !jsonObj.get("releaseRoleUsers").isJsonNull()) {
        JsonArray jsonArrayreleaseRoleUsers = jsonObj.getAsJsonArray("releaseRoleUsers");
        if (jsonArrayreleaseRoleUsers != null) {
          // ensure the json data is an array
          if (!jsonObj.get("releaseRoleUsers").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `releaseRoleUsers` to be an array in the JSON string but got `%s`", jsonObj.get("releaseRoleUsers").toString()));
          }

          // validate the optional field `releaseRoleUsers` (array)
          for (int i = 0; i < jsonArrayreleaseRoleUsers.size(); i++) {
            OpenUserInfoDTO.validateJsonObject(jsonArrayreleaseRoleUsers.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OpenClusterNamespaceRoleUserDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OpenClusterNamespaceRoleUserDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OpenClusterNamespaceRoleUserDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OpenClusterNamespaceRoleUserDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<OpenClusterNamespaceRoleUserDTO>() {
           @Override
           public void write(JsonWriter out, OpenClusterNamespaceRoleUserDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OpenClusterNamespaceRoleUserDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OpenClusterNamespaceRoleUserDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OpenClusterNamespaceRoleUserDTO
  * @throws IOException if the JSON string is invalid with respect to OpenClusterNamespaceRoleUserDTO
  */
  public static OpenClusterNamespaceRoleUserDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OpenClusterNamespaceRoleUserDTO.class);
  }

 /**
  * Convert an instance of OpenClusterNamespaceRoleUserDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
