/*
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.OpenReleaseDTO;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * OpenInstanceConfigDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class OpenInstanceConfigDTO {
  public static final String SERIALIZED_NAME_RELEASE = "release";
  @SerializedName(SERIALIZED_NAME_RELEASE)
  private OpenReleaseDTO release;

  public static final String SERIALIZED_NAME_RELEASE_DELIVERY_TIME = "releaseDeliveryTime";
  @SerializedName(SERIALIZED_NAME_RELEASE_DELIVERY_TIME)
  private String releaseDeliveryTime;

  public static final String SERIALIZED_NAME_DATA_CHANGE_LAST_MODIFIED_TIME = "dataChangeLastModifiedTime";
  @SerializedName(SERIALIZED_NAME_DATA_CHANGE_LAST_MODIFIED_TIME)
  private String dataChangeLastModifiedTime;

  public OpenInstanceConfigDTO() {
  }

  public OpenInstanceConfigDTO release(OpenReleaseDTO release) {

    this.release = release;
    return this;
  }

   /**
   * Get release
   * @return release
  **/
  @javax.annotation.Nullable
  public OpenReleaseDTO getRelease() {
    return release;
  }


  public void setRelease(OpenReleaseDTO release) {
    this.release = release;
  }


  public OpenInstanceConfigDTO releaseDeliveryTime(String releaseDeliveryTime) {

    this.releaseDeliveryTime = releaseDeliveryTime;
    return this;
  }

   /**
   * 配置下发时间（ISO 8601）
   * @return releaseDeliveryTime
  **/
  @javax.annotation.Nullable
  public String getReleaseDeliveryTime() {
    return releaseDeliveryTime;
  }


  public void setReleaseDeliveryTime(String releaseDeliveryTime) {
    this.releaseDeliveryTime = releaseDeliveryTime;
  }


  public OpenInstanceConfigDTO dataChangeLastModifiedTime(String dataChangeLastModifiedTime) {

    this.dataChangeLastModifiedTime = dataChangeLastModifiedTime;
    return this;
  }

   /**
   * 最后修改时间（ISO 8601）
   * @return dataChangeLastModifiedTime
  **/
  @javax.annotation.Nullable
  public String getDataChangeLastModifiedTime() {
    return dataChangeLastModifiedTime;
  }


  public void setDataChangeLastModifiedTime(String dataChangeLastModifiedTime) {
    this.dataChangeLastModifiedTime = dataChangeLastModifiedTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenInstanceConfigDTO openInstanceConfigDTO = (OpenInstanceConfigDTO) o;
    return Objects.equals(this.release, openInstanceConfigDTO.release) &&
        Objects.equals(this.releaseDeliveryTime, openInstanceConfigDTO.releaseDeliveryTime) &&
        Objects.equals(this.dataChangeLastModifiedTime, openInstanceConfigDTO.dataChangeLastModifiedTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(release, releaseDeliveryTime, dataChangeLastModifiedTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenInstanceConfigDTO {\n");
    sb.append("    release: ").append(toIndentedString(release)).append("\n");
    sb.append("    releaseDeliveryTime: ").append(toIndentedString(releaseDeliveryTime)).append("\n");
    sb.append("    dataChangeLastModifiedTime: ").append(toIndentedString(dataChangeLastModifiedTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("release");
    openapiFields.add("releaseDeliveryTime");
    openapiFields.add("dataChangeLastModifiedTime");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to OpenInstanceConfigDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!OpenInstanceConfigDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OpenInstanceConfigDTO is not found in the empty JSON string", OpenInstanceConfigDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!OpenInstanceConfigDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OpenInstanceConfigDTO` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `release`
      if (jsonObj.get("release") != null && !jsonObj.get("release").isJsonNull()) {
        OpenReleaseDTO.validateJsonObject(jsonObj.getAsJsonObject("release"));
      }
      if ((jsonObj.get("releaseDeliveryTime") != null && !jsonObj.get("releaseDeliveryTime").isJsonNull()) && !jsonObj.get("releaseDeliveryTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `releaseDeliveryTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("releaseDeliveryTime").toString()));
      }
      if ((jsonObj.get("dataChangeLastModifiedTime") != null && !jsonObj.get("dataChangeLastModifiedTime").isJsonNull()) && !jsonObj.get("dataChangeLastModifiedTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dataChangeLastModifiedTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dataChangeLastModifiedTime").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OpenInstanceConfigDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OpenInstanceConfigDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OpenInstanceConfigDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OpenInstanceConfigDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<OpenInstanceConfigDTO>() {
           @Override
           public void write(JsonWriter out, OpenInstanceConfigDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OpenInstanceConfigDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OpenInstanceConfigDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OpenInstanceConfigDTO
  * @throws IOException if the JSON string is invalid with respect to OpenInstanceConfigDTO
  */
  public static OpenInstanceConfigDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OpenInstanceConfigDTO.class);
  }

 /**
  * Convert an instance of OpenInstanceConfigDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
