# coding: utf-8

# flake8: noqa

"""
    Apollo OpenAPI

    Apollo配置中心OpenAPI接口文档  ## 认证方式  所有API接口都需要通过Authorization header进行身份验证。  ### 获取Token的方式：  1. **Portal管理界面获取**：    - 登录Apollo Portal管理界面    - 进入\"管理员工具\" -> \"开放平台授权管理\"    - 创建第三方应用，获取Token  2. **Token格式**：    ```    Authorization: token_value    ```  3. **Token权限**：    - Token具有对应应用的读写权限    - 不同Token可能有不同的环境和命名空间权限    - 建议为不同用途创建不同的Token  ### 使用示例： ```bash curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\      -H \"Authorization: your_token_here\" ``` 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.0.1"

# Define package exports
__all__ = [
    "AppManagementApi",
    "ClusterManagementApi",
    "InstanceManagementApi",
    "ItemManagementApi",
    "NamespaceBranchManagementApi",
    "NamespaceManagementApi",
    "OrganizationManagementApi",
    "ReleaseManagementApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Change",
    "ClusterDTO",
    "EntityPairKVEntity",
    "EnvClusterInfo",
    "ItemChangeSets",
    "ItemDTO",
    "KVEntity",
    "ListItemDiffs",
    "ListReleaseBO",
    "MapString",
    "NamespaceGrayDelReleaseDTO",
    "NamespaceIdentifier",
    "NamespaceReleaseDTO",
    "NamespaceSyncModel",
    "NamespaceTextModel",
    "OpenAppDTO",
    "OpenAppNamespaceDTO",
    "OpenClusterDTO",
    "OpenCreateAppDTO",
    "OpenEnvClusterDTO",
    "OpenGrayReleaseRuleDTO",
    "OpenGrayReleaseRuleItemDTO",
    "OpenInstanceConfigDTO",
    "OpenInstanceDTO",
    "OpenItemDTO",
    "OpenNamespaceDTO",
    "OpenNamespaceLockDTO",
    "OpenOrganizationDto",
    "OpenPageDTOOpenInstanceDTO",
    "OpenPageDTOOpenItemDTO",
    "OpenReleaseDTO",
    "OpenapiV1AppsGet401Response",
    "OpenapiV1AppsPost400Response",
    "OpenapiV1AppsPostRequest",
    "OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsValidatePost200Response",
    "OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsValidatePost400Response",
    "OpenapiV1EnvsEnvReleasesCompareGet200Response",
    "ReleaseDTO",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from apollo_openapi.api.app_management_api import AppManagementApi as AppManagementApi
    from apollo_openapi.api.cluster_management_api import ClusterManagementApi as ClusterManagementApi
    from apollo_openapi.api.instance_management_api import InstanceManagementApi as InstanceManagementApi
    from apollo_openapi.api.item_management_api import ItemManagementApi as ItemManagementApi
    from apollo_openapi.api.namespace_branch_management_api import NamespaceBranchManagementApi as NamespaceBranchManagementApi
    from apollo_openapi.api.namespace_management_api import NamespaceManagementApi as NamespaceManagementApi
    from apollo_openapi.api.organization_management_api import OrganizationManagementApi as OrganizationManagementApi
    from apollo_openapi.api.release_management_api import ReleaseManagementApi as ReleaseManagementApi
    
    # import ApiClient
    from apollo_openapi.api_response import ApiResponse as ApiResponse
    from apollo_openapi.api_client import ApiClient as ApiClient
    from apollo_openapi.configuration import Configuration as Configuration
    from apollo_openapi.exceptions import OpenApiException as OpenApiException
    from apollo_openapi.exceptions import ApiTypeError as ApiTypeError
    from apollo_openapi.exceptions import ApiValueError as ApiValueError
    from apollo_openapi.exceptions import ApiKeyError as ApiKeyError
    from apollo_openapi.exceptions import ApiAttributeError as ApiAttributeError
    from apollo_openapi.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from apollo_openapi.models.change import Change as Change
    from apollo_openapi.models.cluster_dto import ClusterDTO as ClusterDTO
    from apollo_openapi.models.entity_pair_kv_entity import EntityPairKVEntity as EntityPairKVEntity
    from apollo_openapi.models.env_cluster_info import EnvClusterInfo as EnvClusterInfo
    from apollo_openapi.models.item_change_sets import ItemChangeSets as ItemChangeSets
    from apollo_openapi.models.item_dto import ItemDTO as ItemDTO
    from apollo_openapi.models.kv_entity import KVEntity as KVEntity
    from apollo_openapi.models.list_item_diffs import ListItemDiffs as ListItemDiffs
    from apollo_openapi.models.list_release_bo import ListReleaseBO as ListReleaseBO
    from apollo_openapi.models.map_string import MapString as MapString
    from apollo_openapi.models.namespace_gray_del_release_dto import NamespaceGrayDelReleaseDTO as NamespaceGrayDelReleaseDTO
    from apollo_openapi.models.namespace_identifier import NamespaceIdentifier as NamespaceIdentifier
    from apollo_openapi.models.namespace_release_dto import NamespaceReleaseDTO as NamespaceReleaseDTO
    from apollo_openapi.models.namespace_sync_model import NamespaceSyncModel as NamespaceSyncModel
    from apollo_openapi.models.namespace_text_model import NamespaceTextModel as NamespaceTextModel
    from apollo_openapi.models.open_app_dto import OpenAppDTO as OpenAppDTO
    from apollo_openapi.models.open_app_namespace_dto import OpenAppNamespaceDTO as OpenAppNamespaceDTO
    from apollo_openapi.models.open_cluster_dto import OpenClusterDTO as OpenClusterDTO
    from apollo_openapi.models.open_create_app_dto import OpenCreateAppDTO as OpenCreateAppDTO
    from apollo_openapi.models.open_env_cluster_dto import OpenEnvClusterDTO as OpenEnvClusterDTO
    from apollo_openapi.models.open_gray_release_rule_dto import OpenGrayReleaseRuleDTO as OpenGrayReleaseRuleDTO
    from apollo_openapi.models.open_gray_release_rule_item_dto import OpenGrayReleaseRuleItemDTO as OpenGrayReleaseRuleItemDTO
    from apollo_openapi.models.open_instance_config_dto import OpenInstanceConfigDTO as OpenInstanceConfigDTO
    from apollo_openapi.models.open_instance_dto import OpenInstanceDTO as OpenInstanceDTO
    from apollo_openapi.models.open_item_dto import OpenItemDTO as OpenItemDTO
    from apollo_openapi.models.open_namespace_dto import OpenNamespaceDTO as OpenNamespaceDTO
    from apollo_openapi.models.open_namespace_lock_dto import OpenNamespaceLockDTO as OpenNamespaceLockDTO
    from apollo_openapi.models.open_organization_dto import OpenOrganizationDto as OpenOrganizationDto
    from apollo_openapi.models.open_page_dto_open_instance_dto import OpenPageDTOOpenInstanceDTO as OpenPageDTOOpenInstanceDTO
    from apollo_openapi.models.open_page_dto_open_item_dto import OpenPageDTOOpenItemDTO as OpenPageDTOOpenItemDTO
    from apollo_openapi.models.open_release_dto import OpenReleaseDTO as OpenReleaseDTO
    from apollo_openapi.models.openapi_v1_apps_get401_response import OpenapiV1AppsGet401Response as OpenapiV1AppsGet401Response
    from apollo_openapi.models.openapi_v1_apps_post400_response import OpenapiV1AppsPost400Response as OpenapiV1AppsPost400Response
    from apollo_openapi.models.openapi_v1_apps_post_request import OpenapiV1AppsPostRequest as OpenapiV1AppsPostRequest
    from apollo_openapi.models.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_items_validate_post200_response import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsValidatePost200Response as OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsValidatePost200Response
    from apollo_openapi.models.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_items_validate_post400_response import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsValidatePost400Response as OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsValidatePost400Response
    from apollo_openapi.models.openapi_v1_envs_env_releases_compare_get200_response import OpenapiV1EnvsEnvReleasesCompareGet200Response as OpenapiV1EnvsEnvReleasesCompareGet200Response
    from apollo_openapi.models.release_dto import ReleaseDTO as ReleaseDTO
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from apollo_openapi.api.app_management_api import AppManagementApi as AppManagementApi
from apollo_openapi.api.cluster_management_api import ClusterManagementApi as ClusterManagementApi
from apollo_openapi.api.instance_management_api import InstanceManagementApi as InstanceManagementApi
from apollo_openapi.api.item_management_api import ItemManagementApi as ItemManagementApi
from apollo_openapi.api.namespace_branch_management_api import NamespaceBranchManagementApi as NamespaceBranchManagementApi
from apollo_openapi.api.namespace_management_api import NamespaceManagementApi as NamespaceManagementApi
from apollo_openapi.api.organization_management_api import OrganizationManagementApi as OrganizationManagementApi
from apollo_openapi.api.release_management_api import ReleaseManagementApi as ReleaseManagementApi

# import ApiClient
from apollo_openapi.api_response import ApiResponse as ApiResponse
from apollo_openapi.api_client import ApiClient as ApiClient
from apollo_openapi.configuration import Configuration as Configuration
from apollo_openapi.exceptions import OpenApiException as OpenApiException
from apollo_openapi.exceptions import ApiTypeError as ApiTypeError
from apollo_openapi.exceptions import ApiValueError as ApiValueError
from apollo_openapi.exceptions import ApiKeyError as ApiKeyError
from apollo_openapi.exceptions import ApiAttributeError as ApiAttributeError
from apollo_openapi.exceptions import ApiException as ApiException

# import models into sdk package
from apollo_openapi.models.change import Change as Change
from apollo_openapi.models.cluster_dto import ClusterDTO as ClusterDTO
from apollo_openapi.models.entity_pair_kv_entity import EntityPairKVEntity as EntityPairKVEntity
from apollo_openapi.models.env_cluster_info import EnvClusterInfo as EnvClusterInfo
from apollo_openapi.models.item_change_sets import ItemChangeSets as ItemChangeSets
from apollo_openapi.models.item_dto import ItemDTO as ItemDTO
from apollo_openapi.models.kv_entity import KVEntity as KVEntity
from apollo_openapi.models.list_item_diffs import ListItemDiffs as ListItemDiffs
from apollo_openapi.models.list_release_bo import ListReleaseBO as ListReleaseBO
from apollo_openapi.models.map_string import MapString as MapString
from apollo_openapi.models.namespace_gray_del_release_dto import NamespaceGrayDelReleaseDTO as NamespaceGrayDelReleaseDTO
from apollo_openapi.models.namespace_identifier import NamespaceIdentifier as NamespaceIdentifier
from apollo_openapi.models.namespace_release_dto import NamespaceReleaseDTO as NamespaceReleaseDTO
from apollo_openapi.models.namespace_sync_model import NamespaceSyncModel as NamespaceSyncModel
from apollo_openapi.models.namespace_text_model import NamespaceTextModel as NamespaceTextModel
from apollo_openapi.models.open_app_dto import OpenAppDTO as OpenAppDTO
from apollo_openapi.models.open_app_namespace_dto import OpenAppNamespaceDTO as OpenAppNamespaceDTO
from apollo_openapi.models.open_cluster_dto import OpenClusterDTO as OpenClusterDTO
from apollo_openapi.models.open_create_app_dto import OpenCreateAppDTO as OpenCreateAppDTO
from apollo_openapi.models.open_env_cluster_dto import OpenEnvClusterDTO as OpenEnvClusterDTO
from apollo_openapi.models.open_gray_release_rule_dto import OpenGrayReleaseRuleDTO as OpenGrayReleaseRuleDTO
from apollo_openapi.models.open_gray_release_rule_item_dto import OpenGrayReleaseRuleItemDTO as OpenGrayReleaseRuleItemDTO
from apollo_openapi.models.open_instance_config_dto import OpenInstanceConfigDTO as OpenInstanceConfigDTO
from apollo_openapi.models.open_instance_dto import OpenInstanceDTO as OpenInstanceDTO
from apollo_openapi.models.open_item_dto import OpenItemDTO as OpenItemDTO
from apollo_openapi.models.open_namespace_dto import OpenNamespaceDTO as OpenNamespaceDTO
from apollo_openapi.models.open_namespace_lock_dto import OpenNamespaceLockDTO as OpenNamespaceLockDTO
from apollo_openapi.models.open_organization_dto import OpenOrganizationDto as OpenOrganizationDto
from apollo_openapi.models.open_page_dto_open_instance_dto import OpenPageDTOOpenInstanceDTO as OpenPageDTOOpenInstanceDTO
from apollo_openapi.models.open_page_dto_open_item_dto import OpenPageDTOOpenItemDTO as OpenPageDTOOpenItemDTO
from apollo_openapi.models.open_release_dto import OpenReleaseDTO as OpenReleaseDTO
from apollo_openapi.models.openapi_v1_apps_get401_response import OpenapiV1AppsGet401Response as OpenapiV1AppsGet401Response
from apollo_openapi.models.openapi_v1_apps_post400_response import OpenapiV1AppsPost400Response as OpenapiV1AppsPost400Response
from apollo_openapi.models.openapi_v1_apps_post_request import OpenapiV1AppsPostRequest as OpenapiV1AppsPostRequest
from apollo_openapi.models.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_items_validate_post200_response import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsValidatePost200Response as OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsValidatePost200Response
from apollo_openapi.models.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_items_validate_post400_response import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsValidatePost400Response as OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsValidatePost400Response
from apollo_openapi.models.openapi_v1_envs_env_releases_compare_get200_response import OpenapiV1EnvsEnvReleasesCompareGet200Response as OpenapiV1EnvsEnvReleasesCompareGet200Response
from apollo_openapi.models.release_dto import ReleaseDTO as ReleaseDTO

""",
            name=__name__,
            doc=__doc__,
        )
    )
