# coding: utf-8

"""
    Apollo OpenAPI

    Apollo配置中心OpenAPI接口文档  ## 认证方式  所有API接口都需要通过Authorization header进行身份验证。  ### 获取Token的方式：  1. **Portal管理界面获取**：    - 登录Apollo Portal管理界面    - 进入\"管理员工具\" -> \"开放平台授权管理\"    - 创建第三方应用，获取Token  2. **Token格式**：    ```    Authorization: token_value    ```  3. **Token权限**：    - Token具有对应应用的读写权限    - 不同Token可能有不同的环境和命名空间权限    - 建议为不同用途创建不同的Token  ### 使用示例： ```bash curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\      -H \"Authorization: your_token_here\" ``` 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ReleaseDTO(BaseModel):
    """
    ReleaseDTO
    """ # noqa: E501
    data_change_created_by: Optional[StrictStr] = Field(default=None, alias="dataChangeCreatedBy")
    data_change_last_modified_by: Optional[StrictStr] = Field(default=None, alias="dataChangeLastModifiedBy")
    data_change_created_by_display_name: Optional[StrictStr] = Field(default=None, alias="dataChangeCreatedByDisplayName")
    data_change_last_modified_by_display_name: Optional[StrictStr] = Field(default=None, alias="dataChangeLastModifiedByDisplayName")
    data_change_created_time: Optional[StrictStr] = Field(default=None, alias="dataChangeCreatedTime")
    data_change_last_modified_time: Optional[StrictStr] = Field(default=None, alias="dataChangeLastModifiedTime")
    id: Optional[StrictInt] = None
    release_key: Optional[StrictStr] = Field(default=None, alias="releaseKey")
    name: Optional[StrictStr] = None
    app_id: Optional[StrictStr] = Field(default=None, alias="appId")
    cluster_name: Optional[StrictStr] = Field(default=None, alias="clusterName")
    namespace_name: Optional[StrictStr] = Field(default=None, alias="namespaceName")
    configurations: Optional[StrictStr] = None
    comment: Optional[StrictStr] = None
    is_abandoned: Optional[StrictBool] = Field(default=None, alias="isAbandoned")
    __properties: ClassVar[List[str]] = ["dataChangeCreatedBy", "dataChangeLastModifiedBy", "dataChangeCreatedByDisplayName", "dataChangeLastModifiedByDisplayName", "dataChangeCreatedTime", "dataChangeLastModifiedTime", "id", "releaseKey", "name", "appId", "clusterName", "namespaceName", "configurations", "comment", "isAbandoned"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReleaseDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReleaseDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dataChangeCreatedBy": obj.get("dataChangeCreatedBy"),
            "dataChangeLastModifiedBy": obj.get("dataChangeLastModifiedBy"),
            "dataChangeCreatedByDisplayName": obj.get("dataChangeCreatedByDisplayName"),
            "dataChangeLastModifiedByDisplayName": obj.get("dataChangeLastModifiedByDisplayName"),
            "dataChangeCreatedTime": obj.get("dataChangeCreatedTime"),
            "dataChangeLastModifiedTime": obj.get("dataChangeLastModifiedTime"),
            "id": obj.get("id"),
            "releaseKey": obj.get("releaseKey"),
            "name": obj.get("name"),
            "appId": obj.get("appId"),
            "clusterName": obj.get("clusterName"),
            "namespaceName": obj.get("namespaceName"),
            "configurations": obj.get("configurations"),
            "comment": obj.get("comment"),
            "isAbandoned": obj.get("isAbandoned")
        })
        return _obj


