# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import apollo_openapi
from apollo_openapi.paths.openapi_v1_apps_app_id_namespaces_namespace_name_roles_role_type import delete  # noqa: E501
from apollo_openapi import configuration, schemas, api_client

from .. import ApiTestMixin


class TestOpenapiV1AppsAppIdNamespacesNamespaceNameRolesRoleType(ApiTestMixin, unittest.TestCase):
    """
    OpenapiV1AppsAppIdNamespacesNamespaceNameRolesRoleType unit test stubs
        移除Namespace角色 (new added)  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = delete.ApiFordelete(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200
    response_body = ''


if __name__ == '__main__':
    unittest.main()
