/* tslint:disable */
/* eslint-disable */
/**
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OpenItemDTO } from './OpenItemDTO';
import {
    OpenItemDTOFromJSON,
    OpenItemDTOFromJSONTyped,
    OpenItemDTOToJSON,
} from './OpenItemDTO';
import type { OpenNamespaceIdentifier } from './OpenNamespaceIdentifier';
import {
    OpenNamespaceIdentifierFromJSON,
    OpenNamespaceIdentifierFromJSONTyped,
    OpenNamespaceIdentifierToJSON,
} from './OpenNamespaceIdentifier';

/**
 *
 * @export
 * @interface OpenItemDiffDTO
 */
export interface OpenItemDiffDTO {
    /**
     * 查找结果
     * @type {number}
     * @memberof OpenItemDiffDTO
     */
    code?: number;
    /**
     * 查找结果信息
     * @type {string}
     * @memberof OpenItemDiffDTO
     */
    message?: string;
    /**
     *
     * @type {OpenNamespaceIdentifier}
     * @memberof OpenItemDiffDTO
     */
    namespace?: OpenNamespaceIdentifier;
    /**
     *
     * @type {Array<OpenItemDTO>}
     * @memberof OpenItemDiffDTO
     */
    createItems?: Array<OpenItemDTO>;
    /**
     *
     * @type {Array<OpenItemDTO>}
     * @memberof OpenItemDiffDTO
     */
    deleteItems?: Array<OpenItemDTO>;
    /**
     *
     * @type {Array<OpenItemDTO>}
     * @memberof OpenItemDiffDTO
     */
    updateItems?: Array<OpenItemDTO>;
}

/**
 * Check if a given object implements the OpenItemDiffDTO interface.
 */
export function instanceOfOpenItemDiffDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OpenItemDiffDTOFromJSON(json: any): OpenItemDiffDTO {
    return OpenItemDiffDTOFromJSONTyped(json, false);
}

export function OpenItemDiffDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenItemDiffDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'namespace': !exists(json, 'namespace') ? undefined : OpenNamespaceIdentifierFromJSON(json['namespace']),
        'createItems': !exists(json, 'createItems') ? undefined : ((json['createItems'] as Array<any>).map(OpenItemDTOFromJSON)),
        'deleteItems': !exists(json, 'deleteItems') ? undefined : ((json['deleteItems'] as Array<any>).map(OpenItemDTOFromJSON)),
        'updateItems': !exists(json, 'updateItems') ? undefined : ((json['updateItems'] as Array<any>).map(OpenItemDTOFromJSON)),
    };
}

export function OpenItemDiffDTOToJSON(value?: OpenItemDiffDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'code': value.code,
        'message': value.message,
        'namespace': OpenNamespaceIdentifierToJSON(value.namespace),
        'createItems': value.createItems === undefined ? undefined : ((value.createItems as Array<any>).map(OpenItemDTOToJSON)),
        'deleteItems': value.deleteItems === undefined ? undefined : ((value.deleteItems as Array<any>).map(OpenItemDTOToJSON)),
        'updateItems': value.updateItems === undefined ? undefined : ((value.updateItems as Array<any>).map(OpenItemDTOToJSON)),
    };
}
