/* tslint:disable */
/* eslint-disable */
/**
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OpenReleaseDTO } from './OpenReleaseDTO';
import {
    OpenReleaseDTOFromJSON,
    OpenReleaseDTOFromJSONTyped,
    OpenReleaseDTOToJSON,
} from './OpenReleaseDTO';

/**
 *
 * @export
 * @interface OpenInstanceConfigDTO
 */
export interface OpenInstanceConfigDTO {
    /**
     *
     * @type {OpenReleaseDTO}
     * @memberof OpenInstanceConfigDTO
     */
    release?: OpenReleaseDTO;
    /**
     * 配置下发时间（ISO 8601）
     * @type {string}
     * @memberof OpenInstanceConfigDTO
     */
    releaseDeliveryTime?: string;
    /**
     * 最后修改时间（ISO 8601）
     * @type {string}
     * @memberof OpenInstanceConfigDTO
     */
    dataChangeLastModifiedTime?: string;
}

/**
 * Check if a given object implements the OpenInstanceConfigDTO interface.
 */
export function instanceOfOpenInstanceConfigDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OpenInstanceConfigDTOFromJSON(json: any): OpenInstanceConfigDTO {
    return OpenInstanceConfigDTOFromJSONTyped(json, false);
}

export function OpenInstanceConfigDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenInstanceConfigDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'release': !exists(json, 'release') ? undefined : OpenReleaseDTOFromJSON(json['release']),
        'releaseDeliveryTime': !exists(json, 'releaseDeliveryTime') ? undefined : json['releaseDeliveryTime'],
        'dataChangeLastModifiedTime': !exists(json, 'dataChangeLastModifiedTime') ? undefined : json['dataChangeLastModifiedTime'],
    };
}

export function OpenInstanceConfigDTOToJSON(value?: OpenInstanceConfigDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'release': OpenReleaseDTOToJSON(value.release),
        'releaseDeliveryTime': value.releaseDeliveryTime,
        'dataChangeLastModifiedTime': value.dataChangeLastModifiedTime,
    };
}
