/* tslint:disable */
/* eslint-disable */
/**
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OpenUserInfoDTO } from './OpenUserInfoDTO';
import {
    OpenUserInfoDTOFromJSON,
    OpenUserInfoDTOFromJSONTyped,
    OpenUserInfoDTOToJSON,
} from './OpenUserInfoDTO';

/**
 *
 * @export
 * @interface OpenEnvNamespaceRoleUserDTO
 */
export interface OpenEnvNamespaceRoleUserDTO {
    /**
     *
     * @type {string}
     * @memberof OpenEnvNamespaceRoleUserDTO
     */
    appId?: string;
    /**
     *
     * @type {string}
     * @memberof OpenEnvNamespaceRoleUserDTO
     */
    namespaceName?: string;
    /**
     *
     * @type {Array<OpenUserInfoDTO>}
     * @memberof OpenEnvNamespaceRoleUserDTO
     */
    modifyRoleUsers?: Array<OpenUserInfoDTO>;
    /**
     *
     * @type {Array<OpenUserInfoDTO>}
     * @memberof OpenEnvNamespaceRoleUserDTO
     */
    releaseRoleUsers?: Array<OpenUserInfoDTO>;
    /**
     *
     * @type {string}
     * @memberof OpenEnvNamespaceRoleUserDTO
     */
    env?: string;
}

/**
 * Check if a given object implements the OpenEnvNamespaceRoleUserDTO interface.
 */
export function instanceOfOpenEnvNamespaceRoleUserDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OpenEnvNamespaceRoleUserDTOFromJSON(json: any): OpenEnvNamespaceRoleUserDTO {
    return OpenEnvNamespaceRoleUserDTOFromJSONTyped(json, false);
}

export function OpenEnvNamespaceRoleUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenEnvNamespaceRoleUserDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'appId': !exists(json, 'appId') ? undefined : json['appId'],
        'namespaceName': !exists(json, 'namespaceName') ? undefined : json['namespaceName'],
        'modifyRoleUsers': !exists(json, 'modifyRoleUsers') ? undefined : ((json['modifyRoleUsers'] as Array<any>).map(OpenUserInfoDTOFromJSON)),
        'releaseRoleUsers': !exists(json, 'releaseRoleUsers') ? undefined : ((json['releaseRoleUsers'] as Array<any>).map(OpenUserInfoDTOFromJSON)),
        'env': !exists(json, 'env') ? undefined : json['env'],
    };
}

export function OpenEnvNamespaceRoleUserDTOToJSON(value?: OpenEnvNamespaceRoleUserDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'appId': value.appId,
        'namespaceName': value.namespaceName,
        'modifyRoleUsers': value.modifyRoleUsers === undefined ? undefined : ((value.modifyRoleUsers as Array<any>).map(OpenUserInfoDTOToJSON)),
        'releaseRoleUsers': value.releaseRoleUsers === undefined ? undefined : ((value.releaseRoleUsers as Array<any>).map(OpenUserInfoDTOToJSON)),
        'env': value.env,
    };
}
