/* tslint:disable */
/* eslint-disable */
/**
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OpenReleaseChangeDTO
 */
export interface OpenReleaseChangeDTO {
    /**
     * 修改类型
     * @type {string}
     * @memberof OpenReleaseChangeDTO
     */
    changeType?: string;
    /**
     * key
     * @type {string}
     * @memberof OpenReleaseChangeDTO
     */
    key?: string;
    /**
     * new value
     * @type {string}
     * @memberof OpenReleaseChangeDTO
     */
    newValue?: string;
    /**
     * old value
     * @type {string}
     * @memberof OpenReleaseChangeDTO
     */
    oldValue?: string;
}

/**
 * Check if a given object implements the OpenReleaseChangeDTO interface.
 */
export function instanceOfOpenReleaseChangeDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OpenReleaseChangeDTOFromJSON(json: any): OpenReleaseChangeDTO {
    return OpenReleaseChangeDTOFromJSONTyped(json, false);
}

export function OpenReleaseChangeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenReleaseChangeDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'changeType': !exists(json, 'changeType') ? undefined : json['changeType'],
        'key': !exists(json, 'key') ? undefined : json['key'],
        'newValue': !exists(json, 'newValue') ? undefined : json['newValue'],
        'oldValue': !exists(json, 'oldValue') ? undefined : json['oldValue'],
    };
}

export function OpenReleaseChangeDTOToJSON(value?: OpenReleaseChangeDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'changeType': value.changeType,
        'key': value.key,
        'newValue': value.newValue,
        'oldValue': value.oldValue,
    };
}
