/*
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ExceptionResponse;
import org.openapitools.client.model.OpenClusterDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClusterManagementApi
 */
@Disabled
public class ClusterManagementApiTest {

    private final ClusterManagementApi api = new ClusterManagementApi();

    /**
     * 创建集群 (original openapi)
     *
     * POST /openapi/v1/envs/{env}/apps/{appId}/clusters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createClusterTest() throws ApiException {
        String appId = null;
        String env = null;
        OpenClusterDTO openClusterDTO = null;
        OpenClusterDTO response = api.createCluster(appId, env, openClusterDTO);
        // TODO: test validations
    }

    /**
     * 删除集群 (new added)
     *
     * DELETE /openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteClusterTest() throws ApiException {
        String env = null;
        String appId = null;
        String clusterName = null;
        String operator = null;
        Object response = api.deleteCluster(env, appId, clusterName, operator);
        // TODO: test validations
    }

    /**
     * 获取指定集群信息 (original openapi)
     *
     * GET /openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getClusterTest() throws ApiException {
        String appId = null;
        String clusterName = null;
        String env = null;
        OpenClusterDTO response = api.getCluster(appId, clusterName, env);
        // TODO: test validations
    }

}
