import typing_extensions

from apollo_openapi.paths import PathValues
from apollo_openapi.apis.paths.openapi_v1_apps import OpenapiV1Apps
from apollo_openapi.apis.paths.openapi_v1_apps_authorized import OpenapiV1AppsAuthorized
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envclusters import OpenapiV1AppsAppIdEnvclusters
from apollo_openapi.apis.paths.openapi_v1_apps_app_id import OpenapiV1AppsAppId
from apollo_openapi.apis.paths.openapi_v1_apps_by_self import OpenapiV1AppsBySelf
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_env_cluster_info import OpenapiV1AppsAppIdEnvClusterInfo
from apollo_openapi.apis.paths.openapi_v1_apps_envs_env import OpenapiV1AppsEnvsEnv
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_miss_envs import OpenapiV1AppsAppIdMissEnvs
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_items_key import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsKey
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_items import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItems
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_encoded_items_key import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameEncodedItemsKey
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_branches_branch_name_items import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameItems
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_items_diff import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsDiff
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_items_synchronize import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsSynchronize
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_items_validation import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsValidation
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_items_revocation import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsRevocation
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name import OpenapiV1EnvsEnvAppsAppIdClustersClusterName
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters import OpenapiV1EnvsEnvAppsAppIdClusters
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_releases import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameReleases
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_releases_latest import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameReleasesLatest
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_branches_branch_name_merge import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameMerge
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_branches_branch_name_releases import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameReleases
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_branches_branch_name_gray_del_releases import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameGrayDelReleases
from apollo_openapi.apis.paths.openapi_v1_envs_env_releases_release_id_rollback import OpenapiV1EnvsEnvReleasesReleaseIdRollback
from apollo_openapi.apis.paths.openapi_v1_envs_env_releases_release_id import OpenapiV1EnvsEnvReleasesReleaseId
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_releases_active import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameReleasesActive
from apollo_openapi.apis.paths.openapi_v1_envs_env_releases_comparison import OpenapiV1EnvsEnvReleasesComparison
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_instances import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameInstances
from apollo_openapi.apis.paths.openapi_v1_envs_env_instances_by_release import OpenapiV1EnvsEnvInstancesByRelease
from apollo_openapi.apis.paths.openapi_v1_envs_env_instances_by_namespace import OpenapiV1EnvsEnvInstancesByNamespace
from apollo_openapi.apis.paths.openapi_v1_envs_env_instances_by_namespace_and_releases_not_in import OpenapiV1EnvsEnvInstancesByNamespaceAndReleasesNotIn
from apollo_openapi.apis.paths.openapi_v1_namespaces import OpenapiV1Namespaces
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_appnamespaces_namespace_name_usage import OpenapiV1AppsAppIdAppnamespacesNamespaceNameUsage
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_appnamespaces import OpenapiV1AppsAppIdAppnamespaces
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespaces
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceName
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_associated_public_namespace import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameAssociatedPublicNamespace
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_lock import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameLock
from apollo_openapi.apis.paths.openapi_v1_appnamespaces import OpenapiV1Appnamespaces
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_appnamespaces_namespace_name import OpenapiV1AppsAppIdAppnamespacesNamespaceName
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_namespaces_releases_status import OpenapiV1AppsAppIdNamespacesReleasesStatus
from apollo_openapi.apis.paths.openapi_v1_envs_env_appnamespaces_public_namespace_name_instances import OpenapiV1EnvsEnvAppnamespacesPublicNamespaceNameInstances
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_namespaces_namespace_name_usage import OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesNamespaceNameUsage
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_missing_namespaces import OpenapiV1AppsAppIdEnvsEnvClustersClusterNameMissingNamespaces
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_namespaces_namespace_name import OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesNamespaceName
from apollo_openapi.apis.paths.openapi_v1_organizations import OpenapiV1Organizations
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_branches import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranches
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_branches_branch_name import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchName
from apollo_openapi.apis.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_branches_branch_name_rules import OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameRules
from apollo_openapi.apis.paths.openapi_v1_envs import OpenapiV1Envs
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_namespaces_namespace_name_permission_init import OpenapiV1AppsAppIdNamespacesNamespaceNamePermissionInit
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_namespaces_permission_init import OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesPermissionInit
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_permissions_permission_type import OpenapiV1AppsAppIdPermissionsPermissionType
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_namespaces_namespace_name_permissions_permission_type import OpenapiV1AppsAppIdNamespacesNamespaceNamePermissionsPermissionType
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envs_env_namespaces_namespace_name_permissions_permission_type import OpenapiV1AppsAppIdEnvsEnvNamespacesNamespaceNamePermissionsPermissionType
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_namespaces_permissions_permission_type import OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesPermissionsPermissionType
from apollo_openapi.apis.paths.openapi_v1_permissions_root import OpenapiV1PermissionsRoot
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envs_env_namespaces_namespace_name_role_users import OpenapiV1AppsAppIdEnvsEnvNamespacesNamespaceNameRoleUsers
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envs_env_namespaces_namespace_name_roles_role_type import OpenapiV1AppsAppIdEnvsEnvNamespacesNamespaceNameRolesRoleType
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_namespaces_role_users import OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesRoleUsers
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_roles_role_type import OpenapiV1AppsAppIdEnvsEnvClustersClusterNameRolesRoleType
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_namespaces_namespace_name_role_users import OpenapiV1AppsAppIdNamespacesNamespaceNameRoleUsers
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_namespaces_namespace_name_roles_role_type import OpenapiV1AppsAppIdNamespacesNamespaceNameRolesRoleType
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_role_users import OpenapiV1AppsAppIdRoleUsers
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_roles_role_type import OpenapiV1AppsAppIdRolesRoleType
from apollo_openapi.apis.paths.openapi_v1_system_roles_create_application import OpenapiV1SystemRolesCreateApplication
from apollo_openapi.apis.paths.openapi_v1_system_roles_create_application_role_users import OpenapiV1SystemRolesCreateApplicationRoleUsers
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_roles_master import OpenapiV1AppsAppIdRolesMaster
from apollo_openapi.apis.paths.openapi_v1_system_role_manage_app_master import OpenapiV1SystemRoleManageAppMaster
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envs_env_accesskeys import OpenapiV1AppsAppIdEnvsEnvAccesskeys
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envs_env_accesskeys_access_key_id import OpenapiV1AppsAppIdEnvsEnvAccesskeysAccessKeyId
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envs_env_accesskeys_access_key_id_activation import OpenapiV1AppsAppIdEnvsEnvAccesskeysAccessKeyIdActivation
from apollo_openapi.apis.paths.openapi_v1_apps_app_id_envs_env_accesskeys_access_key_id_deactivation import OpenapiV1AppsAppIdEnvsEnvAccesskeysAccessKeyIdDeactivation

PathToApi = typing_extensions.TypedDict(
    'PathToApi',
    {
        PathValues.OPENAPI_V1_APPS: OpenapiV1Apps,
        PathValues.OPENAPI_V1_APPS_AUTHORIZED: OpenapiV1AppsAuthorized,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVCLUSTERS: OpenapiV1AppsAppIdEnvclusters,
        PathValues.OPENAPI_V1_APPS_APP_ID: OpenapiV1AppsAppId,
        PathValues.OPENAPI_V1_APPS_BYSELF: OpenapiV1AppsBySelf,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVCLUSTERINFO: OpenapiV1AppsAppIdEnvClusterInfo,
        PathValues.OPENAPI_V1_APPS_ENVS_ENV: OpenapiV1AppsEnvsEnv,
        PathValues.OPENAPI_V1_APPS_APP_ID_MISSENVS: OpenapiV1AppsAppIdMissEnvs,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ITEMS_KEY: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsKey,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ITEMS: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItems,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ENCODED_ITEMS_KEY: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameEncodedItemsKey,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_BRANCHES_BRANCH_NAME_ITEMS: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameItems,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ITEMS_DIFF: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsDiff,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ITEMS_SYNCHRONIZE: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsSynchronize,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ITEMS_VALIDATION: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsValidation,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ITEMS_REVOCATION: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsRevocation,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME: OpenapiV1EnvsEnvAppsAppIdClustersClusterName,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS: OpenapiV1EnvsEnvAppsAppIdClusters,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_RELEASES: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameReleases,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_RELEASES_LATEST: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameReleasesLatest,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_BRANCHES_BRANCH_NAME_MERGE: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameMerge,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_BRANCHES_BRANCH_NAME_RELEASES: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameReleases,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_BRANCHES_BRANCH_NAME_GRAYDELRELEASES: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameGrayDelReleases,
        PathValues.OPENAPI_V1_ENVS_ENV_RELEASES_RELEASE_ID_ROLLBACK: OpenapiV1EnvsEnvReleasesReleaseIdRollback,
        PathValues.OPENAPI_V1_ENVS_ENV_RELEASES_RELEASE_ID: OpenapiV1EnvsEnvReleasesReleaseId,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_RELEASES_ACTIVE: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameReleasesActive,
        PathValues.OPENAPI_V1_ENVS_ENV_RELEASES_COMPARISON: OpenapiV1EnvsEnvReleasesComparison,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_INSTANCES: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameInstances,
        PathValues.OPENAPI_V1_ENVS_ENV_INSTANCES_BYRELEASE: OpenapiV1EnvsEnvInstancesByRelease,
        PathValues.OPENAPI_V1_ENVS_ENV_INSTANCES_BYNAMESPACE: OpenapiV1EnvsEnvInstancesByNamespace,
        PathValues.OPENAPI_V1_ENVS_ENV_INSTANCES_BYNAMESPACEANDRELEASESNOTIN: OpenapiV1EnvsEnvInstancesByNamespaceAndReleasesNotIn,
        PathValues.OPENAPI_V1_NAMESPACES: OpenapiV1Namespaces,
        PathValues.OPENAPI_V1_APPS_APP_ID_APPNAMESPACES_NAMESPACE_NAME_USAGE: OpenapiV1AppsAppIdAppnamespacesNamespaceNameUsage,
        PathValues.OPENAPI_V1_APPS_APP_ID_APPNAMESPACES: OpenapiV1AppsAppIdAppnamespaces,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespaces,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceName,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ASSOCIATEDPUBLICNAMESPACE: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameAssociatedPublicNamespace,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_LOCK: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameLock,
        PathValues.OPENAPI_V1_APPNAMESPACES: OpenapiV1Appnamespaces,
        PathValues.OPENAPI_V1_APPS_APP_ID_APPNAMESPACES_NAMESPACE_NAME: OpenapiV1AppsAppIdAppnamespacesNamespaceName,
        PathValues.OPENAPI_V1_APPS_APP_ID_NAMESPACES_RELEASES_STATUS: OpenapiV1AppsAppIdNamespacesReleasesStatus,
        PathValues.OPENAPI_V1_ENVS_ENV_APPNAMESPACES_PUBLIC_NAMESPACE_NAME_INSTANCES: OpenapiV1EnvsEnvAppnamespacesPublicNamespaceNameInstances,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_USAGE: OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesNamespaceNameUsage,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_CLUSTERS_CLUSTER_NAME_MISSINGNAMESPACES: OpenapiV1AppsAppIdEnvsEnvClustersClusterNameMissingNamespaces,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME: OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesNamespaceName,
        PathValues.OPENAPI_V1_ORGANIZATIONS: OpenapiV1Organizations,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_BRANCHES: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranches,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_BRANCHES_BRANCH_NAME: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchName,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_BRANCHES_BRANCH_NAME_RULES: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameRules,
        PathValues.OPENAPI_V1_ENVS: OpenapiV1Envs,
        PathValues.OPENAPI_V1_APPS_APP_ID_NAMESPACES_NAMESPACE_NAME_PERMISSIONINIT: OpenapiV1AppsAppIdNamespacesNamespaceNamePermissionInit,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_CLUSTERS_CLUSTER_NAME_NAMESPACES_PERMISSIONINIT: OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesPermissionInit,
        PathValues.OPENAPI_V1_APPS_APP_ID_PERMISSIONS_PERMISSION_TYPE: OpenapiV1AppsAppIdPermissionsPermissionType,
        PathValues.OPENAPI_V1_APPS_APP_ID_NAMESPACES_NAMESPACE_NAME_PERMISSIONS_PERMISSION_TYPE: OpenapiV1AppsAppIdNamespacesNamespaceNamePermissionsPermissionType,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_NAMESPACES_NAMESPACE_NAME_PERMISSIONS_PERMISSION_TYPE: OpenapiV1AppsAppIdEnvsEnvNamespacesNamespaceNamePermissionsPermissionType,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_CLUSTERS_CLUSTER_NAME_NAMESPACES_PERMISSIONS_PERMISSION_TYPE: OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesPermissionsPermissionType,
        PathValues.OPENAPI_V1_PERMISSIONS_ROOT: OpenapiV1PermissionsRoot,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_NAMESPACES_NAMESPACE_NAME_ROLEUSERS: OpenapiV1AppsAppIdEnvsEnvNamespacesNamespaceNameRoleUsers,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_NAMESPACES_NAMESPACE_NAME_ROLES_ROLE_TYPE: OpenapiV1AppsAppIdEnvsEnvNamespacesNamespaceNameRolesRoleType,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_CLUSTERS_CLUSTER_NAME_NAMESPACES_ROLEUSERS: OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesRoleUsers,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_CLUSTERS_CLUSTER_NAME_ROLES_ROLE_TYPE: OpenapiV1AppsAppIdEnvsEnvClustersClusterNameRolesRoleType,
        PathValues.OPENAPI_V1_APPS_APP_ID_NAMESPACES_NAMESPACE_NAME_ROLEUSERS: OpenapiV1AppsAppIdNamespacesNamespaceNameRoleUsers,
        PathValues.OPENAPI_V1_APPS_APP_ID_NAMESPACES_NAMESPACE_NAME_ROLES_ROLE_TYPE: OpenapiV1AppsAppIdNamespacesNamespaceNameRolesRoleType,
        PathValues.OPENAPI_V1_APPS_APP_ID_ROLEUSERS: OpenapiV1AppsAppIdRoleUsers,
        PathValues.OPENAPI_V1_APPS_APP_ID_ROLES_ROLE_TYPE: OpenapiV1AppsAppIdRolesRoleType,
        PathValues.OPENAPI_V1_SYSTEM_ROLES_CREATEAPPLICATION: OpenapiV1SystemRolesCreateApplication,
        PathValues.OPENAPI_V1_SYSTEM_ROLES_CREATEAPPLICATION_ROLEUSERS: OpenapiV1SystemRolesCreateApplicationRoleUsers,
        PathValues.OPENAPI_V1_APPS_APP_ID_ROLES_MASTER: OpenapiV1AppsAppIdRolesMaster,
        PathValues.OPENAPI_V1_SYSTEM_ROLE_MANAGEAPPMASTER: OpenapiV1SystemRoleManageAppMaster,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_ACCESSKEYS: OpenapiV1AppsAppIdEnvsEnvAccesskeys,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_ACCESSKEYS_ACCESS_KEY_ID: OpenapiV1AppsAppIdEnvsEnvAccesskeysAccessKeyId,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_ACCESSKEYS_ACCESS_KEY_ID_ACTIVATION: OpenapiV1AppsAppIdEnvsEnvAccesskeysAccessKeyIdActivation,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_ACCESSKEYS_ACCESS_KEY_ID_DEACTIVATION: OpenapiV1AppsAppIdEnvsEnvAccesskeysAccessKeyIdDeactivation,
    }
)

path_to_api = PathToApi(
    {
        PathValues.OPENAPI_V1_APPS: OpenapiV1Apps,
        PathValues.OPENAPI_V1_APPS_AUTHORIZED: OpenapiV1AppsAuthorized,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVCLUSTERS: OpenapiV1AppsAppIdEnvclusters,
        PathValues.OPENAPI_V1_APPS_APP_ID: OpenapiV1AppsAppId,
        PathValues.OPENAPI_V1_APPS_BYSELF: OpenapiV1AppsBySelf,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVCLUSTERINFO: OpenapiV1AppsAppIdEnvClusterInfo,
        PathValues.OPENAPI_V1_APPS_ENVS_ENV: OpenapiV1AppsEnvsEnv,
        PathValues.OPENAPI_V1_APPS_APP_ID_MISSENVS: OpenapiV1AppsAppIdMissEnvs,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ITEMS_KEY: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsKey,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ITEMS: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItems,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ENCODED_ITEMS_KEY: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameEncodedItemsKey,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_BRANCHES_BRANCH_NAME_ITEMS: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameItems,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ITEMS_DIFF: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsDiff,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ITEMS_SYNCHRONIZE: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsSynchronize,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ITEMS_VALIDATION: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsValidation,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ITEMS_REVOCATION: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItemsRevocation,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME: OpenapiV1EnvsEnvAppsAppIdClustersClusterName,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS: OpenapiV1EnvsEnvAppsAppIdClusters,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_RELEASES: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameReleases,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_RELEASES_LATEST: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameReleasesLatest,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_BRANCHES_BRANCH_NAME_MERGE: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameMerge,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_BRANCHES_BRANCH_NAME_RELEASES: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameReleases,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_BRANCHES_BRANCH_NAME_GRAYDELRELEASES: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameGrayDelReleases,
        PathValues.OPENAPI_V1_ENVS_ENV_RELEASES_RELEASE_ID_ROLLBACK: OpenapiV1EnvsEnvReleasesReleaseIdRollback,
        PathValues.OPENAPI_V1_ENVS_ENV_RELEASES_RELEASE_ID: OpenapiV1EnvsEnvReleasesReleaseId,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_RELEASES_ACTIVE: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameReleasesActive,
        PathValues.OPENAPI_V1_ENVS_ENV_RELEASES_COMPARISON: OpenapiV1EnvsEnvReleasesComparison,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_INSTANCES: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameInstances,
        PathValues.OPENAPI_V1_ENVS_ENV_INSTANCES_BYRELEASE: OpenapiV1EnvsEnvInstancesByRelease,
        PathValues.OPENAPI_V1_ENVS_ENV_INSTANCES_BYNAMESPACE: OpenapiV1EnvsEnvInstancesByNamespace,
        PathValues.OPENAPI_V1_ENVS_ENV_INSTANCES_BYNAMESPACEANDRELEASESNOTIN: OpenapiV1EnvsEnvInstancesByNamespaceAndReleasesNotIn,
        PathValues.OPENAPI_V1_NAMESPACES: OpenapiV1Namespaces,
        PathValues.OPENAPI_V1_APPS_APP_ID_APPNAMESPACES_NAMESPACE_NAME_USAGE: OpenapiV1AppsAppIdAppnamespacesNamespaceNameUsage,
        PathValues.OPENAPI_V1_APPS_APP_ID_APPNAMESPACES: OpenapiV1AppsAppIdAppnamespaces,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespaces,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceName,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_ASSOCIATEDPUBLICNAMESPACE: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameAssociatedPublicNamespace,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_LOCK: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameLock,
        PathValues.OPENAPI_V1_APPNAMESPACES: OpenapiV1Appnamespaces,
        PathValues.OPENAPI_V1_APPS_APP_ID_APPNAMESPACES_NAMESPACE_NAME: OpenapiV1AppsAppIdAppnamespacesNamespaceName,
        PathValues.OPENAPI_V1_APPS_APP_ID_NAMESPACES_RELEASES_STATUS: OpenapiV1AppsAppIdNamespacesReleasesStatus,
        PathValues.OPENAPI_V1_ENVS_ENV_APPNAMESPACES_PUBLIC_NAMESPACE_NAME_INSTANCES: OpenapiV1EnvsEnvAppnamespacesPublicNamespaceNameInstances,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_USAGE: OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesNamespaceNameUsage,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_CLUSTERS_CLUSTER_NAME_MISSINGNAMESPACES: OpenapiV1AppsAppIdEnvsEnvClustersClusterNameMissingNamespaces,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME: OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesNamespaceName,
        PathValues.OPENAPI_V1_ORGANIZATIONS: OpenapiV1Organizations,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_BRANCHES: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranches,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_BRANCHES_BRANCH_NAME: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchName,
        PathValues.OPENAPI_V1_ENVS_ENV_APPS_APP_ID_CLUSTERS_CLUSTER_NAME_NAMESPACES_NAMESPACE_NAME_BRANCHES_BRANCH_NAME_RULES: OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameBranchesBranchNameRules,
        PathValues.OPENAPI_V1_ENVS: OpenapiV1Envs,
        PathValues.OPENAPI_V1_APPS_APP_ID_NAMESPACES_NAMESPACE_NAME_PERMISSIONINIT: OpenapiV1AppsAppIdNamespacesNamespaceNamePermissionInit,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_CLUSTERS_CLUSTER_NAME_NAMESPACES_PERMISSIONINIT: OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesPermissionInit,
        PathValues.OPENAPI_V1_APPS_APP_ID_PERMISSIONS_PERMISSION_TYPE: OpenapiV1AppsAppIdPermissionsPermissionType,
        PathValues.OPENAPI_V1_APPS_APP_ID_NAMESPACES_NAMESPACE_NAME_PERMISSIONS_PERMISSION_TYPE: OpenapiV1AppsAppIdNamespacesNamespaceNamePermissionsPermissionType,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_NAMESPACES_NAMESPACE_NAME_PERMISSIONS_PERMISSION_TYPE: OpenapiV1AppsAppIdEnvsEnvNamespacesNamespaceNamePermissionsPermissionType,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_CLUSTERS_CLUSTER_NAME_NAMESPACES_PERMISSIONS_PERMISSION_TYPE: OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesPermissionsPermissionType,
        PathValues.OPENAPI_V1_PERMISSIONS_ROOT: OpenapiV1PermissionsRoot,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_NAMESPACES_NAMESPACE_NAME_ROLEUSERS: OpenapiV1AppsAppIdEnvsEnvNamespacesNamespaceNameRoleUsers,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_NAMESPACES_NAMESPACE_NAME_ROLES_ROLE_TYPE: OpenapiV1AppsAppIdEnvsEnvNamespacesNamespaceNameRolesRoleType,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_CLUSTERS_CLUSTER_NAME_NAMESPACES_ROLEUSERS: OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesRoleUsers,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_CLUSTERS_CLUSTER_NAME_ROLES_ROLE_TYPE: OpenapiV1AppsAppIdEnvsEnvClustersClusterNameRolesRoleType,
        PathValues.OPENAPI_V1_APPS_APP_ID_NAMESPACES_NAMESPACE_NAME_ROLEUSERS: OpenapiV1AppsAppIdNamespacesNamespaceNameRoleUsers,
        PathValues.OPENAPI_V1_APPS_APP_ID_NAMESPACES_NAMESPACE_NAME_ROLES_ROLE_TYPE: OpenapiV1AppsAppIdNamespacesNamespaceNameRolesRoleType,
        PathValues.OPENAPI_V1_APPS_APP_ID_ROLEUSERS: OpenapiV1AppsAppIdRoleUsers,
        PathValues.OPENAPI_V1_APPS_APP_ID_ROLES_ROLE_TYPE: OpenapiV1AppsAppIdRolesRoleType,
        PathValues.OPENAPI_V1_SYSTEM_ROLES_CREATEAPPLICATION: OpenapiV1SystemRolesCreateApplication,
        PathValues.OPENAPI_V1_SYSTEM_ROLES_CREATEAPPLICATION_ROLEUSERS: OpenapiV1SystemRolesCreateApplicationRoleUsers,
        PathValues.OPENAPI_V1_APPS_APP_ID_ROLES_MASTER: OpenapiV1AppsAppIdRolesMaster,
        PathValues.OPENAPI_V1_SYSTEM_ROLE_MANAGEAPPMASTER: OpenapiV1SystemRoleManageAppMaster,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_ACCESSKEYS: OpenapiV1AppsAppIdEnvsEnvAccesskeys,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_ACCESSKEYS_ACCESS_KEY_ID: OpenapiV1AppsAppIdEnvsEnvAccesskeysAccessKeyId,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_ACCESSKEYS_ACCESS_KEY_ID_ACTIVATION: OpenapiV1AppsAppIdEnvsEnvAccesskeysAccessKeyIdActivation,
        PathValues.OPENAPI_V1_APPS_APP_ID_ENVS_ENV_ACCESSKEYS_ACCESS_KEY_ID_DEACTIVATION: OpenapiV1AppsAppIdEnvsEnvAccesskeysAccessKeyIdDeactivation,
    }
)
