# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import apollo_openapi
from apollo_openapi.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_namespaces_permission_init import post  # noqa: E501
from apollo_openapi import configuration, schemas, api_client

from .. import ApiTestMixin


class TestOpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesPermissionInit(ApiTestMixin, unittest.TestCase):
    """
    OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesPermissionInit unit test stubs
        初始化集群Namespace权限 (new added)  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200
    response_body = ''


if __name__ == '__main__':
    unittest.main()
