from apollo_openapi.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_items.get import ApiForget
from apollo_openapi.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_items.put import ApiForput
from apollo_openapi.paths.openapi_v1_envs_env_apps_app_id_clusters_cluster_name_namespaces_namespace_name_items.post import ApiForpost


class OpenapiV1EnvsEnvAppsAppIdClustersClusterNameNamespacesNamespaceNameItems(
    ApiForget,
    ApiForput,
    ApiForpost,
):
    pass
