from apollo_openapi.paths.openapi_v1_apps_app_id_envs_env_clusters_cluster_name_namespaces_namespace_name_public_association.get import ApiForget


class OpenapiV1AppsAppIdEnvsEnvClustersClusterNameNamespacesNamespaceNamePublicAssociation(
    ApiForget,
):
    pass
