# coding: utf-8

"""
    Apollo OpenAPI

    <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "apollo-openapi"
VERSION = "0.0.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi >= 14.5.14",
    "frozendict ~= 2.3.4",
    "python-dateutil ~= 2.7.0",
    "setuptools >= 21.0.0",
    "typing_extensions ~= 4.3.0",
    "urllib3 ~= 1.26.7",
]

setup(
    name=NAME,
    version=VERSION,
    description="Apollo OpenAPI",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Apollo OpenAPI"],
    python_requires=">=3.7",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    &lt;p&gt;Apollo配置中心OpenAPI接口文档&lt;/p&gt;  &lt;h2&gt;认证方式&lt;/h2&gt; &lt;p&gt;所有 API 接口都需要通过 &lt;code&gt;Authorization&lt;/code&gt; header 进行身份验证。&lt;/p&gt;  &lt;h3&gt;获取 Token 的方式：&lt;/h3&gt; &lt;ol&gt;   &lt;li&gt;&lt;b&gt;Portal 管理界面获取&lt;/b&gt;：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。&lt;/li&gt;   &lt;li&gt;&lt;b&gt;Token 格式&lt;/b&gt;：&lt;code&gt;Authorization: token_value&lt;/code&gt;&lt;/li&gt;   &lt;li&gt;&lt;b&gt;Token 权限&lt;/b&gt;：按应用/环境/命名空间授予，建议不同用途分别创建。&lt;/li&gt; &lt;/ol&gt;  &lt;h3&gt;使用示例&lt;/h3&gt; &lt;pre&gt;&lt;code class&#x3D;\&quot;language-bash\&quot;&gt;curl -X GET \&quot;http://localhost:8070/openapi/v1/apps\&quot; \\ -H \&quot;Authorization: your_token_here\&quot;&lt;/code&gt;&lt;/pre&gt;   # noqa: E501
    """
)
