/* tslint:disable */
/* eslint-disable */
/**
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  OpenAccessKeyDTO,
} from '../models';
import {
    OpenAccessKeyDTOFromJSON,
    OpenAccessKeyDTOToJSON,
} from '../models';

export interface CreateAccessKeyRequest {
    appId: string;
    env: string;
    operator?: string;
}

export interface DeleteAccessKeyRequest {
    appId: string;
    env: string;
    accessKeyId: number;
    operator?: string;
}

export interface DisableAccessKeyRequest {
    appId: string;
    env: string;
    accessKeyId: number;
}

export interface EnableAccessKeyRequest {
    appId: string;
    env: string;
    accessKeyId: number;
    mode?: number;
}

export interface FindAccessKeysRequest {
    appId: string;
    env: string;
}

/**
 *
 */
export class AccessKeyManagementApi extends runtime.BaseAPI {

    /**
     *
     * 创建AccessKey
     */
    async createAccessKeyRaw(requestParameters: CreateAccessKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OpenAccessKeyDTO>> {
        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling createAccessKey.');
        }

        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling createAccessKey.');
        }

        const queryParameters: any = {};

        if (requestParameters.operator !== undefined) {
            queryParameters['operator'] = requestParameters.operator;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apps/{appId}/envs/{env}/accesskeys`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters.appId))).replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OpenAccessKeyDTOFromJSON(jsonValue));
    }

    /**
     *
     * 创建AccessKey
     */
    async createAccessKey(requestParameters: CreateAccessKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OpenAccessKeyDTO> {
        const response = await this.createAccessKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     *
     * 删除AccessKey
     */
    async deleteAccessKeyRaw(requestParameters: DeleteAccessKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling deleteAccessKey.');
        }

        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling deleteAccessKey.');
        }

        if (requestParameters.accessKeyId === null || requestParameters.accessKeyId === undefined) {
            throw new runtime.RequiredError('accessKeyId','Required parameter requestParameters.accessKeyId was null or undefined when calling deleteAccessKey.');
        }

        const queryParameters: any = {};

        if (requestParameters.operator !== undefined) {
            queryParameters['operator'] = requestParameters.operator;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apps/{appId}/envs/{env}/accesskeys/{accessKeyId}`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters.appId))).replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))).replace(`{${"accessKeyId"}}`, encodeURIComponent(String(requestParameters.accessKeyId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     *
     * 删除AccessKey
     */
    async deleteAccessKey(requestParameters: DeleteAccessKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAccessKeyRaw(requestParameters, initOverrides);
    }

    /**
     *
     * 禁用AccessKey
     */
    async disableAccessKeyRaw(requestParameters: DisableAccessKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling disableAccessKey.');
        }

        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling disableAccessKey.');
        }

        if (requestParameters.accessKeyId === null || requestParameters.accessKeyId === undefined) {
            throw new runtime.RequiredError('accessKeyId','Required parameter requestParameters.accessKeyId was null or undefined when calling disableAccessKey.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apps/{appId}/envs/{env}/accesskeys/{accessKeyId}/deactivation`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters.appId))).replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))).replace(`{${"accessKeyId"}}`, encodeURIComponent(String(requestParameters.accessKeyId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     *
     * 禁用AccessKey
     */
    async disableAccessKey(requestParameters: DisableAccessKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.disableAccessKeyRaw(requestParameters, initOverrides);
    }

    /**
     *
     * 启用AccessKey
     */
    async enableAccessKeyRaw(requestParameters: EnableAccessKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling enableAccessKey.');
        }

        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling enableAccessKey.');
        }

        if (requestParameters.accessKeyId === null || requestParameters.accessKeyId === undefined) {
            throw new runtime.RequiredError('accessKeyId','Required parameter requestParameters.accessKeyId was null or undefined when calling enableAccessKey.');
        }

        const queryParameters: any = {};

        if (requestParameters.mode !== undefined) {
            queryParameters['mode'] = requestParameters.mode;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apps/{appId}/envs/{env}/accesskeys/{accessKeyId}/activation`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters.appId))).replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))).replace(`{${"accessKeyId"}}`, encodeURIComponent(String(requestParameters.accessKeyId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     *
     * 启用AccessKey
     */
    async enableAccessKey(requestParameters: EnableAccessKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.enableAccessKeyRaw(requestParameters, initOverrides);
    }

    /**
     *
     * 查找AccessKey
     */
    async findAccessKeysRaw(requestParameters: FindAccessKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OpenAccessKeyDTO>>> {
        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling findAccessKeys.');
        }

        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling findAccessKeys.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/apps/{appId}/envs/{env}/accesskeys`.replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters.appId))).replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OpenAccessKeyDTOFromJSON));
    }

    /**
     *
     * 查找AccessKey
     */
    async findAccessKeys(requestParameters: FindAccessKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OpenAccessKeyDTO>> {
        const response = await this.findAccessKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
