/* tslint:disable */
/* eslint-disable */
/**
 * Apollo OpenAPI
 * <p>Apollo配置中心OpenAPI接口文档</p>  <h2>认证方式</h2> <p>所有 API 接口都需要通过 <code>Authorization</code> header 进行身份验证。</p>  <h3>获取 Token 的方式：</h3> <ol>   <li><b>Portal 管理界面获取</b>：登录 Portal → 管理员工具 → 开放平台授权管理 → 创建第三方应用，获取 Token。</li>   <li><b>Token 格式</b>：<code>Authorization: token_value</code></li>   <li><b>Token 权限</b>：按应用/环境/命名空间授予，建议不同用途分别创建。</li> </ol>  <h3>使用示例</h3> <pre><code class=\"language-bash\">curl -X GET \"http://localhost:8070/openapi/v1/apps\" \\ -H \"Authorization: your_token_here\"</code></pre>
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  OpenInstanceDTO,
  OpenInstancePageDTO,
} from '../models';
import {
    OpenInstanceDTOFromJSON,
    OpenInstanceDTOToJSON,
    OpenInstancePageDTOFromJSON,
    OpenInstancePageDTOToJSON,
} from '../models';

export interface GetByNamespaceRequest {
    env: string;
    appId: string;
    clusterName: string;
    namespaceName: string;
    page: number;
    size: number;
    instanceAppId?: string;
}

export interface GetByReleaseRequest {
    env: string;
    releaseId: number;
    page: number;
    size: number;
}

export interface GetByReleasesAndNamespaceNotInRequest {
    env: string;
    appId: string;
    clusterName: string;
    namespaceName: string;
    releaseIds?: string;
}

export interface GetInstanceCountByNamespaceRequest {
    env: string;
    appId: string;
    clusterName: string;
    namespaceName: string;
}

/**
 *
 */
export class InstanceManagementApi extends runtime.BaseAPI {

    /**
     * 根据namespaceName查询实例（new added）
     */
    async getByNamespaceRaw(requestParameters: GetByNamespaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OpenInstancePageDTO>> {
        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling getByNamespace.');
        }

        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling getByNamespace.');
        }

        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getByNamespace.');
        }

        if (requestParameters.namespaceName === null || requestParameters.namespaceName === undefined) {
            throw new runtime.RequiredError('namespaceName','Required parameter requestParameters.namespaceName was null or undefined when calling getByNamespace.');
        }

        if (requestParameters.page === null || requestParameters.page === undefined) {
            throw new runtime.RequiredError('page','Required parameter requestParameters.page was null or undefined when calling getByNamespace.');
        }

        if (requestParameters.size === null || requestParameters.size === undefined) {
            throw new runtime.RequiredError('size','Required parameter requestParameters.size was null or undefined when calling getByNamespace.');
        }

        const queryParameters: any = {};

        if (requestParameters.appId !== undefined) {
            queryParameters['appId'] = requestParameters.appId;
        }

        if (requestParameters.clusterName !== undefined) {
            queryParameters['clusterName'] = requestParameters.clusterName;
        }

        if (requestParameters.namespaceName !== undefined) {
            queryParameters['namespaceName'] = requestParameters.namespaceName;
        }

        if (requestParameters.instanceAppId !== undefined) {
            queryParameters['instanceAppId'] = requestParameters.instanceAppId;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/envs/{env}/instances/by-namespace`.replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OpenInstancePageDTOFromJSON(jsonValue));
    }

    /**
     * 根据namespaceName查询实例（new added）
     */
    async getByNamespace(requestParameters: GetByNamespaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OpenInstancePageDTO> {
        const response = await this.getByNamespaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/envs/{env}/instances/by-release
     * 根据发布版本查询实例（支持分页） (new added)
     */
    async getByReleaseRaw(requestParameters: GetByReleaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OpenInstancePageDTO>> {
        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling getByRelease.');
        }

        if (requestParameters.releaseId === null || requestParameters.releaseId === undefined) {
            throw new runtime.RequiredError('releaseId','Required parameter requestParameters.releaseId was null or undefined when calling getByRelease.');
        }

        if (requestParameters.page === null || requestParameters.page === undefined) {
            throw new runtime.RequiredError('page','Required parameter requestParameters.page was null or undefined when calling getByRelease.');
        }

        if (requestParameters.size === null || requestParameters.size === undefined) {
            throw new runtime.RequiredError('size','Required parameter requestParameters.size was null or undefined when calling getByRelease.');
        }

        const queryParameters: any = {};

        if (requestParameters.releaseId !== undefined) {
            queryParameters['releaseId'] = requestParameters.releaseId;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.size !== undefined) {
            queryParameters['size'] = requestParameters.size;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/envs/{env}/instances/by-release`.replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OpenInstancePageDTOFromJSON(jsonValue));
    }

    /**
     * GET /openapi/v1/envs/{env}/instances/by-release
     * 根据发布版本查询实例（支持分页） (new added)
     */
    async getByRelease(requestParameters: GetByReleaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OpenInstancePageDTO> {
        const response = await this.getByReleaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 查询不在指定发布版本中的实例 (new added)
     */
    async getByReleasesAndNamespaceNotInRaw(requestParameters: GetByReleasesAndNamespaceNotInRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<OpenInstanceDTO>>> {
        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling getByReleasesAndNamespaceNotIn.');
        }

        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling getByReleasesAndNamespaceNotIn.');
        }

        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getByReleasesAndNamespaceNotIn.');
        }

        if (requestParameters.namespaceName === null || requestParameters.namespaceName === undefined) {
            throw new runtime.RequiredError('namespaceName','Required parameter requestParameters.namespaceName was null or undefined when calling getByReleasesAndNamespaceNotIn.');
        }

        const queryParameters: any = {};

        if (requestParameters.appId !== undefined) {
            queryParameters['appId'] = requestParameters.appId;
        }

        if (requestParameters.clusterName !== undefined) {
            queryParameters['clusterName'] = requestParameters.clusterName;
        }

        if (requestParameters.namespaceName !== undefined) {
            queryParameters['namespaceName'] = requestParameters.namespaceName;
        }

        if (requestParameters.releaseIds !== undefined) {
            queryParameters['releaseIds'] = requestParameters.releaseIds;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/envs/{env}/instances/by-namespace-and-releases-not-in`.replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OpenInstanceDTOFromJSON));
    }

    /**
     * 查询不在指定发布版本中的实例 (new added)
     */
    async getByReleasesAndNamespaceNotIn(requestParameters: GetByReleasesAndNamespaceNotInRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<OpenInstanceDTO>> {
        const response = await this.getByReleasesAndNamespaceNotInRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * GET /openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/instances
     * 获取命名空间下的实例数量 (original openapi)
     */
    async getInstanceCountByNamespaceRaw(requestParameters: GetInstanceCountByNamespaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        if (requestParameters.env === null || requestParameters.env === undefined) {
            throw new runtime.RequiredError('env','Required parameter requestParameters.env was null or undefined when calling getInstanceCountByNamespace.');
        }

        if (requestParameters.appId === null || requestParameters.appId === undefined) {
            throw new runtime.RequiredError('appId','Required parameter requestParameters.appId was null or undefined when calling getInstanceCountByNamespace.');
        }

        if (requestParameters.clusterName === null || requestParameters.clusterName === undefined) {
            throw new runtime.RequiredError('clusterName','Required parameter requestParameters.clusterName was null or undefined when calling getInstanceCountByNamespace.');
        }

        if (requestParameters.namespaceName === null || requestParameters.namespaceName === undefined) {
            throw new runtime.RequiredError('namespaceName','Required parameter requestParameters.namespaceName was null or undefined when calling getInstanceCountByNamespace.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/instances`.replace(`{${"env"}}`, encodeURIComponent(String(requestParameters.env))).replace(`{${"appId"}}`, encodeURIComponent(String(requestParameters.appId))).replace(`{${"clusterName"}}`, encodeURIComponent(String(requestParameters.clusterName))).replace(`{${"namespaceName"}}`, encodeURIComponent(String(requestParameters.namespaceName))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * GET /openapi/v1/envs/{env}/apps/{appId}/clusters/{clusterName}/namespaces/{namespaceName}/instances
     * 获取命名空间下的实例数量 (original openapi)
     */
    async getInstanceCountByNamespace(requestParameters: GetInstanceCountByNamespaceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.getInstanceCountByNamespaceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
