name: General CI Checks
on:
 pull_request:
   branches:
     - main

permissions:
 contents: read
 pull-requests: read

jobs:
 commitlint:
   name: Commit Message Check
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: wagoid/commitlint-github-action@v6
 line_lint:
   name: Line Format Check
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: linelint
       uses: hezhangjian/linelint@main
 typos:
   name: Typos Check
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: crate-ci/typos@master
